name: Build and Deploy

on:
  schedule:
    - cron: '0 5 * * 0' # 仅周日凌晨5点触发
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      # 拉取上游 PlotSquared
      - name: Clone Upstream PlotSquared
        run: |
          git clone --depth 1 --branch main https://github.com/IntellectualSites/PlotSquared.git ./external-plotsquared


      # Java 21
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle


      # Gradle Wrapper检查
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6


      # 构建
      - name: Build PlotSquared
        working-directory: ./external-plotsquared
        run: |
          chmod +x gradlew
          ./gradlew clean build


      # 检查jar
      - name: Verify Artifacts
        run: |
          ls -lah ./external-plotsquared/**/build/libs/

          if ! ls ./external-plotsquared/**/build/libs/*.jar; then
            echo "No jar found"
            exit 1
          fi


      # 发布Release
      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build
          name: "Latest PlotSquared Build"
          body: |
            自动 PlotSquared 构建.


            Build:
            ${{ github.run_number }}

          files: |
            external-plotsquared/Core/build/libs/*.jar
            external-plotsquared/Bukkit/build/libs/*.jar

          draft: false
          prerelease: false
          overwrite_files: true
          append_body: false
          make_latest: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}